# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 833e288be13d106fb51f54171536c491df6354917297a49c9ffc72bc2806a86e96e3e01e3d2c77f5e50fd8f5bdeb3ef4d8e56b7d9fc413ade9aa80863593739c

test:
  secret_key_base: df9490f9449fa2c9d395c3d1e51f33c2de2a932966e56df724940082794ba1e4ce4865845f4b18cebd8971d5e2b4bcc50d0bdfc16e0685c9d0b2b2e324575e9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
